service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - "arn:aws:dynamodb:eu-west-1:533267237683:table/products-db"
            - "arn:aws:dynamodb:eu-west-1:533267237683:table/stocks-db"

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
    environment:
      PRODUCTS_TABLE: "products-db"
      STOCKS_TABLE: "stocks-db"

  getProductsById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          request:
            parameters:
              paths:
                productId: true
    environment:
      PRODUCTS_TABLE: "products-db"
      STOCKS_TABLE: "stocks-db"
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
          request:
            schemas:
              application/json: ${file(src/schemas/createProductSchema.json)}
    environment:
      PRODUCTS_TABLE: "products-db"
      STOCKS_TABLE: "stocks-db"
