service: import-service

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: "s3:ListBucket"
      Resource: "arn:aws:s3:::import-products-data-bucket"
    - Effect: Allow
      Action: "s3:*"
      Resource: "arn:aws:s3:::import-products-data-bucket/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
