service: import-service

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: "s3:ListBucket"
      Resource: "arn:aws:s3:::import-products-data-bucket"
    - Effect: Allow
      Action: "s3:*"
      Resource:
        - "arn:aws:s3:::import-products-data-bucket/uploaded/*"
    - Effect: Allow
      Action: "sqs:*"
      Resource:
        Fn::ImportValue: SQSQueueArn

  environment:
    SQS_QUEUE_URL:
      Fn::ImportValue: SQSQueueUrl

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            name: basicAuthorizer
            arn: "arn:aws:lambda:eu-west-1:533267237683:function:authorization-service-dev-basicAuthorizer"
            resultTtlInSeconds: 0
            type: token
            identitySource: method.request.header.Authorization

  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: import-products-data-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
